apiVersion: v1
kind: Service
metadata:
  name: hello2
  namespace: default
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{}}}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello2
  type: ClusterIP