apiVersion: v1
kind: Service
metadata:
  name: hello
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{}}}'
spec:
  ports:
  - port: 80
    name: hello
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello
  type: ClusterIP