# This role binding allows "jane" to read pods in the "default" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: owner-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: owner-account # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-owner # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""
